persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

listener 1883
protocol mqtt
allow_anonymous true

listener 8883
protocol mqtt
allow_anonymous true
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
